### ISSUE TITLE
Make multi-lines when diffing objects have long `Debug` outputs

### ISSUE THREAD

**Issue by cocuh** [google/assertor#30]
For objects having long `Debug` outputs, current debug message is messed up.

One improvable idea is 

# Example:

```rust
#[derive(Debug, PartialEq)]
struct LongDebugObject<> {
    values: Vec<&'static str>,
    another_value: Option<&'static str>,
}


let actual = vec![
    LongDebugObject {
        values: vec!["a", "c", "t", "u", "a", "l"],
        another_value: None,
    },
    LongDebugObject {
        values: vec![],
        another_value: Some("same value"),
    },
];
let expected = vec![
    LongDebugObject {
        values: vec![],
        another_value: Some("same value"),
    },
    LongDebugObject {
        values: vec!["e", "x", "p", "e", "c", "t", "e", "d"],
        another_value: None,
    },
];
assert_that!(actual).contains_exactly_in_order(expected);
```

### Current
```
missing (1)   : [LongDebugObject { values: ["e", "x", "p", "e", "c", "t", "e", "d"], another_value: None }]
unexpected (1): [LongDebugObject { values: ["a", "c", "t", "u", "a", "l"], another_value: None }]
---
expected      : [LongDebugObject { values: [], another_value: Some("same value") }, LongDebugObject { values: ["e", "x", "p", "e", "c", "t", "e", "d"], another_value: None }]
actual        : [LongDebugObject { values: ["a", "c", "t", "u", "a", "l"], another_value: None }, LongDebugObject { values: [], another_value: Some("same value") }]
```

### Improvement Idea
Make the output of expected / actual values multiple lines instead of single line.

```
missing (1)   : [LongDebugObject { values: ["e", "x", "p", "e", "c", "t", "e", "d"], another_value: None }]
unexpected (1): [LongDebugObject { values: ["a", "c", "t", "u", "a", "l"], another_value: None }]
---
expected      :  [
   - LongDebugObject { values: [], another_value: Some("same value") }
   - LongDebugObject { values: ["e", "x", "p", "e", "c", "t", "e", "d"], another_value: None }
]
actual        : [
   - LongDebugObject { values: ["a", "c", "t", "u", "a", "l"], another_value: None },
   - LongDebugObject { values: [], another_value: Some("same value") }
]
```

**Comment by kelebra** [comment]
Let's follow our collection-like types to make sure we cover all of them with this functionality:

- [ ] `Iter` (will cover `Vec` as well). I will push a PR for that soon.
- [ ] `Map`: when keys or values are large objects, we can discuss further.

**Comment by cocuh** [comment]
Thank you for volunteering and sending a PR.  Let me review your pr.

About desired behavior of map, there are multiple options, let me share my thoughs.  In case when showing different values given a same key ([link](https://github.com/google/assertor/blob/6addc641a5c756e973f2863e6222054c72767da6/src/assertions/map.rs#L359-L366)), desired behavior in my mind is that:

**Current:**
```
key {:?} was mapped to an unexpected value
expected value {:?}, but found {:?}
```

**Idea:**
```
a key was mapped to an unexpected value: {key:?}
expected: {expected:?}
actual   : {actual:?} 
```

About a case when showing tuple of key and value ([link](https://github.com/google/assertor/blob/6addc641a5c756e973f2863e6222054c72767da6/src/assertions/map.rs#L399)), I don't think we should make it multiple line so that one line corresponds to one entry of mapping. 


**Current** ([link](https://github.com/google/assertor/blob/6addc641a5c756e973f2863e6222054c72767da6/src/assertions/map.rs#L398-L400)):

```
entry was not found:   "long long key 1" -> "long long value 1"
entry was not found:   "long long key 2" -> "long long value 2"
```

**Naive idea of multile line:** but I don't think this is a good idea.

```
entry was not found:   "long long key 1"
                                 -> "long long value 1"
entry was not found:   "long long key 2"
                                 -> "long long value 2"
```

There are multiple options, let me know if you have any ideas. :)

**Comment by kelebra** [comment]
Thanks for the initial idea and PR review! Imo we should approach maps with 2 cases in mind:

1) Extra / missing entries ([missing behavior](https://github.com/google/assertor/blob/master/src/assertions/map.rs#L399), [extra behavior](https://github.com/google/assertor/blob/master/src/assertions/map.rs#L425)). There 2 things that look a bit off: first of all we duplicate the prefix on each line `entry was not found: ...` in case of missing and `unexpected entry was found: ...` in case of extra. It would be great if we could reduce it to the following for longer entries:

```
entries were not found: [
  "key1" -> "value1",
  "key2" -> "value2",
  ...
]
```

If entries are small, then this would look like this:

```
entries were not found: ["key1" -> "value1", "key2" -> "value2"]
```

2) Different values ([current behavior](https://github.com/google/assertor/blob/master/src/assertions/map.rs#L360)) should be rendered similarly though this might be harder to achieve. Ideally it should look something like this:

```
key "bla" was mapped to an unexpected value: {
  "expected" : "val1",
  "actual"      : "val2",
}
```

However this approach still results in the noise because we duplicate `key ... was mapped to an unexpected value` for every diff. Arguably we could consolidate like this:

```
keys were mapped to an unexpected values: [
  "key1": {
    "expected" : "val1",
    "actual"      : "val2" 
  }
  ...
]
```

This approach also solves the issue with longer keys and value since it is a newline for every item. However it is challenging since we do not have support for nested `Fact` which seems like a straightforward solution here. We could add this functionality but maybe it should be a separate or even separate issue. Lmk what you think, imo we could definitely address first point as part of this issue and maybe look into 2 in a separate issue.
